### ISSUE TITLE
Can't upgrade to 0.9.1 using meteor update

### ISSUE THREAD

**Issue by doubletaketech** [jonblum/meteor-cropper#4]
After I run meteor update, it tells me
jonblum:jquery-cropper  upgraded from 0.7.8 to 0.9.1

but when I run meteor list, it still shows as 0.7.8

This is with  Meteor 1.1.0.2 

0.9.1 worked for me in previous version of Meteor, but now it doesn't.

Any ideas?
Thanks,
Don

**Comment by jonblum** [comment]
Afraid I'm not sure.  I don't think it would have anything to do with the package itself... since it's about as simple as packages come.  In addition, I know the Meteor 1.1 update rewrote how package version constraints are handled.

Maybe try doing `meteor remove jonblum:jquery-cropper` followed by `meteor add jonblum:jquery-cropper` to reset things?  If that doesn't work, you may want to [file an issue with the meteor devs](https://github.com/meteor/meteor/issues).

**Comment by doubletaketech** [comment]
Must be a bug with latest Meteor.  Remove/Add did not work.  It says it updated to 0.9.1, but it does not.  However, if you force the version in the add, it works.  I'll let them know.
